spring:
  application:
    name: vexora

  datasource:
    url: jdbc:postgresql://localhost:5433/vexora
    username: postgres
    password: postgres

  sql:
    init:
      mode: always
      separator: "^^"

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

